### ISSUE TITLE
SCIM - GET all users work, but a specific users does not

### ISSUE THREAD

**Issue by danflomin** [simpleidserver/SimpleIdServer#276]
Hi,

I've encountered inconsistency between `/users` and `/users/{id}`.

I have a user that I cannot get its resource using `/users/{id}`, though I do get it by querying all users using `/users`.

The exception I get from querying the specific user is:
```
System.NullReferenceException: Object reference not set to an instance of an object.
  ?, in void SCIMRepresentationExtensions.ApplyEmptyArray(SCIMRepresentation representation)+(SCIMRepresentationAttribute a) => { }
  ?, in bool Enumerable.Any<TSource>(IEnumerable<TSource> source, Func<TSource, bool> predicate)
  ?, in void SCIMRepresentationExtensions.ApplyEmptyArray(SCIMRepresentation representation)
  ?, in async Task<IActionResult> BaseApiController.InternalGet(string id)
  ?, in async ValueTask<IActionResult> TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, object controller, object[] arguments)
  ?, in async Task ControllerActionInvoker.InvokeActionMethodAsync()+Awaited(?)
  ?, in async Task ControllerActionInvoker.InvokeNextActionFilterAsync()+Awaited(?)
  ?, in void ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
  ?, in Task ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
  ?, in async Task ControllerActionInvoker.InvokeInnerFilterAsync()+Awaited(?)
  ?, in async Task ResourceInvoker.InvokeNextExceptionFilterAsync()+Awaited(?)
```

Looking at its attributes, I do not see something special.
Attached is a CSV with the user's attributes.
[single-user-scim-data.csv](https://github.com/simpleidserver/SimpleIdServer/files/8853605/single-user-scim-data.csv)

Please let me know if this helps or whether more information is needed.

Thanks 
Dan

**Comment by simpleidserver** [comment]
Hello,

Even with the CSV, it's difficult to reproduce the issue on a local machine because the Schema Attribute Id are different.

The only difference between `GET` and `SEARCH` operations resides in the EntityFrameworkCore configuration.
I think there is an issue in the code `Any(a => a.SchemaAttribute.Name == attr.Name)` when we are trying to resolve the `SchemaAttribute`.

The following modifications have been made in the project :
* Update the project `dotnet6\SimpleIdServer.Scim.SqlServer.Startup` to support the SCIM Schema `urn:ietf:params:scim:schemas:extension:enterprise:2.0:User`.
* Add a mapping between `manager.value` and `id`. In your database the value `manager@gmail.com` is not correct and must match to the Id of SCIM resource representing the user's manager.
* Fix the logic `Any(a => a.SchemaAttribute.Name == attr.Name)`.

Can-you please try the latest changes made on the branch `release/2.0.9` ?

Kind regards,

Sid

**Comment by danflomin** [comment]
Thanks for your quick reply!

I will test it.
I will be away from keyboard for a few days, but once I'm back I will reply about my findings.

**Comment by danflomin** [comment]
Hey,

Unfortunately the problem is not solved.

Attached is the stack trace on branch `release/2.0.9`.

Please let me know what else I can do in order to progress with this issue.

Thanks

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at SimpleIdServer.Scim.Domains.SCIMSchema.<>c__DisplayClass37_0.<HasAttribute>b__0(SCIMSchemaAttribute attr) in /Scim/SimpleIdServer.Scim.Domains/SCIMSchema.cs:line 84
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at SimpleIdServer.Scim.Domains.SCIMSchema.HasAttribute(SCIMSchemaAttribute attribute) in /Scim/SimpleIdServer.Scim.Domains/SCIMSchema.cs:line 84
   at SimpleIdServer.Scim.Domains.SCIMRepresentation.<>c__DisplayClass42_0.<GetSchema>b__0(SCIMSchema s) in /Scim/SimpleIdServer.Scim.Domains/SCIMRepresentation.cs:line 77
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at SimpleIdServer.Scim.Domains.SCIMRepresentation.GetSchema(SCIMSchemaAttribute attribute) in /Scim/SimpleIdServer.Scim.Domains/SCIMRepresentation.cs:line 77
   at SimpleIdServer.Scim.Domains.SCIMRepresentation.GetSchema(SCIMRepresentationAttribute attribute) in /Scim/SimpleIdServer.Scim.Domains/SCIMRepresentation.cs:line 72
   at SimpleIdServer.Scim.Domain.SCIMRepresentationExtensions.<>c__DisplayClass9_0.<ToResponse>b__0(SCIMRepresentationAttribute a) in /Scim/SimpleIdServer.Scim/Extensions/SCIMRepresentationExtensions.cs:line 366
   at System.Linq.Enumerable.SelectListIterator`2.ToArray()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.GetEnumerator()+MoveNext()
   at System.Linq.Lookup`2.Create(IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`2.GetEnumerator()
   at SimpleIdServer.Scim.Domain.SCIMRepresentationExtensions.EnrichResponse(IEnumerable`1 attributes, JObject jObj, Boolean isGetRequest) in /Scim/SimpleIdServer.Scim/Extensions/SCIMRepresentationExtensions.cs:line 468
   at SimpleIdServer.Scim.Domain.SCIMRepresentationExtensions.ToResponse(SCIMRepresentation representation, String location, Boolean isGetRequest, Boolean includeStandardAttributes, Boolean addEmptyArray) in /Scim/SimpleIdServer.Scim/Extensions/SCIMRepresentationExtensions.cs:line 374
   at SimpleIdServer.Scim.Api.BaseApiController.BuildHTTPResult(SCIMRepresentation representation, HttpStatusCode status, Boolean isGetRequest) in /Scim/SimpleIdServer.Scim/Api/BaseApiController.cs:line 385
   at SimpleIdServer.Scim.Api.BaseApiController.InternalGet(String id) in /Scim/SimpleIdServer.Scim/Api/BaseApiController.cs:line 232
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
```

**Comment by simpleidserver** [comment]
Hello,

I reproduced your issue on my local machine & fix it.
There was a problem in the EntityFrameworkCore configuration, in fact the SchemaAttribute wasn't properly loaded.
The fix is pushed in the branch "release/2.0.9", can you please try again ?

Kind regards,

SimpleIdServer

**Comment by danflomin** [comment]
Hey,

Looks good now !

Many thanks for your fast response, you are awesome !

When will you publish the 2.0.9 as a nuget?

**Comment by danflomin** [comment]
How did you manage to reproduce this?
Do you have a test for this issue?

**Comment by simpleidserver** [comment]
I could reproduce your bug on my local machine by using your sample data (single-user-scimdata.csv).
In fact, there was an issue in the algorithm used to set the $ref parameter (enrichment).

I'm going to make a release tomorrow.
