### ISSUE TITLE
[SCIM] support nested groups memberships

### ISSUE THREAD

**Issue by danflomin** [simpleidserver/SimpleIdServer#343]
Hello, how are you?

In RFC7643 section 4.2 it is written that SCIM supports having nested groups.
<img width="627" alt="image" src="https://user-images.githubusercontent.com/33806717/202909268-c1ba3888-46e5-4201-b3aa-93c40e0d8558.png">

When I tried to check it in the current implementation, I get 404s for PATCHing a group as a new member of another group.

I will appreciate your help with adding support of nested groups.

Kind regards
Dan

**Comment by simpleidserver** [comment]
Hello,

Indeed there is an issue in the current implementation.
The problem is fixed in the `master` branch, the following Attribute mapping must be added : 

``` 
Id = Guid.NewGuid().ToString(),
SourceAttributeId = groupSchema.Attributes.First(a => a.Name == "members").Id,
SourceResourceType = StandardSchemas.GroupSchema.ResourceType,
SourceAttributeSelector = "members",
TargetResourceType = StandardSchemas.GroupSchema.ResourceType
```

KR,

SID

**Comment by danflomin** [comment]
Thanks !

Can you please release this as a nuget?

**Comment by simpleidserver** [comment]
The nuget package '2.0.21' is released :)

**Comment by danflomin** [comment]
Hi 
I checked the new version, and it looks like user's groups are not affected by parent groups.

Meaning, if a user is a member of group `A`, which is a sub group of group `B`, the user won't be a member of group `B` according to a GET response.

Is this correct? Should the user also be a member of the parent group?

From looking at the RFC7643 4.1.2, it looks like it should be.

![image](https://user-images.githubusercontent.com/33806717/205677431-71b7f899-926d-4794-bfc4-2d36f64a40c0.png)

Kind regards 
Dan

**Comment by simpleidserver** [comment]
Hello,

Indeed it is an issue. 
The ticket has been added into the release `2.0.22` and will be fixed when migration to dotnet7 is finished (branch 3.0.0).

KR,

SID

**Comment by danflomin** [comment]
Hi 

Thanks a lot.

Is it possible to fix this issue as a minor before the migration to dotnet7?
At the moment our codebase cannot be migrated to dotnet7, so I won't be able to use this fix.


Kind regards
Dan

**Comment by simpleidserver** [comment]
Hello @danflomin ,

The implementation is finished and pushed into the branch `release/2.0.22`.
A new table has been added in order to track the references between Users and groups, this table is required to support this feature.
I'm working on a migration script to populate this table, the ticket will be finished next monday (12/12).

KR,

SID

**Comment by simpleidserver** [comment]
Pre-release package has been published : `dotnet add package SimpleIdServer.Scim --version 2.0.22-ci-00375 --source https://www.myget.org/F/advance-ict/api/v3/index.json`

To use the latest version, your database should be updated via EFCore migration script:

```
// generate migration script
dotnet ef migrations add SupportIndirectReferences
// apply migration script
dotnet ef database update
```

Edit the `Startup.cs` file and update the attribute mapping like this. 
The mapping rule `Groups:members => Users:groups` must have a `Mode` property set to `PROPAGATE_INHERITANCE`.

```
var secondAttributeMapping = new SCIMAttributeMapping
{
   Id = Guid.NewGuid().ToString(),
   SourceAttributeId = groupSchema.Attributes.First(a => a.Name == "members").Id,
   SourceResourceType = StandardSchemas.GroupSchema.ResourceType,
   SourceAttributeSelector = "members",
   TargetResourceType = StandardSchemas.UserSchema.ResourceType,
   TargetAttributeId = userSchema.Attributes.First(a => a.Name == "groups").Id,
   Mode = Mode.PROPAGATE_INHERITANCE
}
```

If your database contains groups which inherit other groups, you can apply the following SQL scripts in the correct order.
They will populate the table `dbo.SCIMRepresentationIndirectReference`.
* https://github.com/simpleidserver/SimpleIdServer/blob/master/Migrations/SCIM/2.0.21To2.0.22/1-ResolveParents.sql
* https://github.com/simpleidserver/SimpleIdServer/blob/master/Migrations/SCIM/2.0.21To2.0.22/2-UpdateIndirectReferences.sql

**Comment by danflomin** [comment]
Hi !

Thank you so much for this effort.

I'm trying to use the new version unsuccessfully.

These are the mappings I use:

```
            var firstAttributeMapping = new SCIMAttributeMapping {
                Id = Guid.NewGuid().ToString(),
                SourceAttributeId = userSchema.Attributes.First(a => a.Name == "groups").Id,
                SourceResourceType = StandardSchemas.UserSchema.ResourceType,
                SourceAttributeSelector = "groups",
                TargetResourceType = StandardSchemas.GroupSchema.ResourceType,
                TargetAttributeId = groupSchema.Attributes.First(a => a.Name == "members").Id
            };
            var secondAttributeMapping = new SCIMAttributeMapping {
                Id = Guid.NewGuid().ToString(),
                SourceAttributeId = groupSchema.Attributes.First(a => a.Name == "members").Id,
                SourceResourceType = StandardSchemas.GroupSchema.ResourceType,
                SourceAttributeSelector = "members",
                TargetResourceType = StandardSchemas.UserSchema.ResourceType,
                TargetAttributeId = userSchema.Attributes.First(a => a.Name == "groups").Id,
                Mode = Mode.PROPAGATE_INHERITANCE
            };
            var thirdAttributeMapping = new SCIMAttributeMapping {
                Id = Guid.NewGuid().ToString(),
                SourceAttributeId = groupSchema.Attributes.First(a => a.Name == "members").Id,
                SourceResourceType = StandardSchemas.GroupSchema.ResourceType,
                SourceAttributeSelector = "members",
                TargetResourceType = StandardSchemas.GroupSchema.ResourceType
            };
```

Then I do the following actions:

1. Create a user
2. Create a group with the user in it
3. Create a parent group with the group in it

When I check the DB, I do not see any indirect references, and when I perform a request to get the user I do not see it is a member of the parent group.
The attributes of the representations looks fine regarding membership relations.

Do you have any idea why this is not working for me?


Kind regards
Dan

**Comment by simpleidserver** [comment]
Hello,

Your configuration is correct, however there is a small bug in the current implementation.
This issue is fixed and a pre-release package has been published.
Can-you please retry by using the following nuget package ?

```
 dotnet add package SimpleIdServer.Scim --version 2.0.23-ci-00378 --source https://www.myget.org/F/advance-ict/api/v3/index.json
```

KR,

SID

**Comment by danflomin** [comment]
Hey :)

I'm sorry for not being responsive lately.

I checked it out and it looks to work now !

I do have a few comments about issues I found:

1. When adding a group as a member of another, the users of the nested group do not get a `RepresentationReferenceAttributeAddedEvent` event published for the indirect membership. I did not check the other event types but I guess that also a removed reference attribute is not being published.
2. There is a regression when updating a group's display name by PATCH. It does not update its name.


Thank you so much for your support.
Kind regards,
Dan

**Comment by simpleidserver** [comment]
Hello !

No problem :)
I made some modifications in the branch `release/v2.0.24` to raise events when indirect memberships are added or removed.
However I couldn't reproduce the second issue, the following HTTP requests have been executed in order and the displayName is correctly updated : 

Create group
```
HTTP POST
{
  "schemas": [
    "urn:ietf:params:scim:schemas:core:2.0:Group"
  ],
  "displayName": "azeaze"
}
```

Update displayName

```
HTTP PATCH
{
  "schemas": [
    "urn:ietf:params:scim:api:messages:2.0:PatchOp"
  ],
  "Operations": [
    {
      "op": "replace",
      "path": "displayName",
      "value": "Hello"
    }
  ]
}
```

Can-you please provide more information in order to reproduce this bug ?

KR,

SID

**Comment by danflomin** [comment]
I'm sorry for the confusion.
The thing is not working is that the new group name is not being propagated to the user when you look for its groups.

**Comment by danflomin** [comment]
That was a quick one !

Is it possible to get a preview nuget so I can check it out?

**Comment by simpleidserver** [comment]
The pre-release package is available here :) 

```
dotnet add package SimpleIdServer.Scim --version 2.0.24-ci-00381 --source https://www.myget.org/F/advance-ict/api/v3/index.json
```

**Comment by danflomin** [comment]
I checked the new version and I see that an event is raised.
Why is it a `RepresentationReferenceAttributeUpdatedEvent`?

Shouldn't it be a `RepresentationReferenceAttributeAddedEvent` for the user with a representation that holds the indirect group?
For example - 
1. Add a user - `RepresentationAddedEvent`
2. Add a group with a user in it - `RepresentationAddedEvent` + `RepresentationReferenceAttributeAddedEvent`
3. Add a group with the first group in it - `RepresentationAddedEvent` + `RepresentationReferenceAttributeAddedEvent` (on the group) + `RepresentationReferenceAttributeAddedEvent` (on the user)

A total of 6 events.

**Comment by danflomin** [comment]
Thanks for the quick response.

In order to check this version I need it to have a nuget version (unfortunately I cannot use it without).
Can you please add it as a nuget?

Kind regards
Dan

**Comment by simpleidserver** [comment]
Oups sorry, you can use the following Nuget package : 

```
dotnet add package SimpleIdServer.Scim --version 2.0.24-ci-00385 --source https://www.myget.org/F/advance-ict/api/v3/index.json
```

**Comment by danflomin** [comment]
Thanks !

I checked it and I see that I now get 2 `RepresentationReferenceAttributeAddedEvent` events, but none of them have 2 groups in the user's representation.

**Comment by simpleidserver** [comment]
Can-you please describe how to reproduce this issue?

**Comment by danflomin** [comment]
Hey

Please follow the these steps:

1. Add a user
2. Add a group with the user in it
3. Add another group with the first group as its member

The third action should invoke a `RepresentationReferenceAttributeAddedEvent` with a representation that has 2 groups in it (1 direct and one indirect)

**Comment by simpleidserver** [comment]
Thank you for the explanation :)
Both issue should be fixed in this release : 

```
dotnet add package SimpleIdServer.Scim --version 2.0.24-ci-00388 --source https://www.myget.org/F/advance-ict/api/v3/index.json
```

**Comment by danflomin** [comment]
It looks like the event issue is fixed! Thanks :)


I now noticed another Issue.

Do the following to reproduce:
1. Create a user
2. Create a group with the user in it
3. Create a parent group with the first group as its member
4. Remove the nested group from the parent group

This results in a `Sequence contains no matching element`.
I think that the issue is in here `FindRootSCIMSchemaByResourceType`, it does a `FirstOrDefault` that throws this error.

**Comment by simpleidserver** [comment]
There was an issue in the algorithm used to purge the children attributes.

New UTS have been added and the Integration Tests are working on my local machine. Following scenarios have been executed :
1. Create a user
2. Create a group with the user in it
3. Create a parent group with the first group as its member
4.1 Remove the parent group (HTTP DELETE)
4.2 Use HTTP PUT to remove the "members" attribute
4.3 Use HTTP PATCH to remove the "members" attribute

The nuget package is `Install-Package SimpleIdServer.Scim -Version 2.0.24-ci-00391 -Source https://www.myget.org/F/advance-ict/api/v3/index.json`.

KR,

SID

**Comment by danflomin** [comment]
Hello 

Currently all my UTs pass as well !

I will take another effort in challenging the current implementation, but I believe we found the sweet spot 🔥 

Thanks a lot

**Comment by danflomin** [comment]
Is it on purpose that the third attribute mapping does not have a `target_attribute_id`? https://github.com/simpleidserver/SimpleIdServer/issues/343#issuecomment-1365751639

**Comment by simpleidserver** [comment]
The third attribute mapping doesn't have `target_attribute_id` because sub group doesn't contain reference to a parent group contrary to user representation which contain `groups` property.

Your migration script seems to be correct to update the mapping attributes :)

**Comment by danflomin** [comment]
Awesome!

Please release this version as a nuget.

Thank you so much for this effort.

**Comment by danflomin** [comment]
Hello

I've been working on deploying the new feature of nested groups, but for some reason the following line sometimes causes a PATCH operation of adding a nested group to a parent group fails.
It says that:

```
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at SimpleIdServer.Scim.Helpers.RepresentationReferenceSync.<>c.<ResolveIndirectChildren>b__9_5(SCIMRepresentationAttribute a)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.SqlNullabilityProcessor.<VisitIn>g__ProcessInExpressionValues|29_0(SqlExpression valuesExpression, Boolean extractNullValues)
   at Microsoft.EntityFrameworkCore.Query.SqlNullabilityProcessor.VisitIn(InExpression inExpression, Boolean allowOptimizedExpansion, Boolean& nullable)
   at Microsoft.EntityFrameworkCore.Query.SqlNullabilityProcessor.Visit(SqlExpression sqlExpression, Boolean allowOptimizedExpansion, Boolean preserveColumnNullabilityInformation, Boolean& nullable)
   at Microsoft.EntityFrameworkCore.Query.SqlNullabilityProcessor.VisitSqlBinary(SqlBinaryExpression sqlBinaryExpression, Boolean allowOptimizedExpansion, Boolean& nullable)
   at Microsoft.EntityFrameworkCore.Query.SqlNullabilityProcessor.Visit(SqlExpression sqlExpression, Boolean allowOptimizedExpansion, Boolean preserveColumnNullabilityInformation, Boolean& nullable)
   at Microsoft.EntityFrameworkCore.Query.SqlNullabilityProcessor.VisitSqlBinary(SqlBinaryExpression sqlBinaryExpression, Boolean allowOptimizedExpansion, Boolean& nullable)
   at Microsoft.EntityFrameworkCore.Query.SqlNullabilityProcessor.Visit(SqlExpression sqlExpression, Boolean allowOptimizedExpansion, Boolean preserveColumnNullabilityInformation, Boolean& nullable)
   at Microsoft.EntityFrameworkCore.Query.SqlNullabilityProcessor.Visit(SqlExpression sqlExpression, Boolean allowOptimizedExpansion, Boolean& nullable)
   at Microsoft.EntityFrameworkCore.Query.SqlNullabilityProcessor.Visit(SelectExpression selectExpression)
   at Microsoft.EntityFrameworkCore.Query.SqlNullabilityProcessor.Process(SelectExpression selectExpression, IReadOnlyDictionary`2 parameterValues, Boolean& canCache)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Query.Internal.NpgsqlParameterBasedSqlProcessor.ProcessSqlNullability(SelectExpression selectExpression, IReadOnlyDictionary`2 parametersValues, Boolean& canCache)
   at Microsoft.EntityFrameworkCore.Query.RelationalParameterBasedSqlProcessor.Optimize(SelectExpression selectExpression, IReadOnlyDictionary`2 parametersValues, Boolean& canCache)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalCommandCache.GetRelationalCommandTemplate(IReadOnlyDictionary`2 parameters)
   at Microsoft.EntityFrameworkCore.Internal.RelationCommandCacheExtensions.RentAndPopulateRelationalCommand(RelationalCommandCache relationalCommandCache, RelationalQueryContext queryContext)
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at SimpleIdServer.Scim.Persistence.EF.EFSCIMRepresentationCommandRepository.FindSCIMRepresentationByIds(IEnumerable`1 representationIds, String resourceType)
   at SimpleIdServer.Scim.Helpers.RepresentationReferenceSync.ResolveIndirectChildren(ICollection`1 patchOperations, SCIMAttributeMapping selfAttributeMapping, SCIMAttributeMapping attributeMapping, List`1 lst)
   at SimpleIdServer.Scim.Helpers.RepresentationReferenceSync.Sync(String resourceType, SCIMRepresentation newSourceScimRepresentation, ICollection`1 patchOperations, String location)
   at SimpleIdServer.Scim.Commands.Handlers.PatchRepresentationCommandHandler.UpdateRepresentation(SCIMRepresentation existingRepresentation, PatchRepresentationCommand patchRepresentationCommand)
   at SimpleIdServer.Scim.Commands.Handlers.PatchRepresentationCommandHandler.Handle(PatchRepresentationCommand patchRepresentationCommand)
   at SimpleIdServer.Scim.Api.BaseApiController.InternalPatch(String id, PatchRepresentationParameter patchRepresentation)
```

https://github.com/simpleidserver/SimpleIdServer/blob/855bd65dc92747f9c2688d14f1604a852b2527da/src/Scim/SimpleIdServer.Scim/Helpers/RepresentationReferenceSync.cs#L231


Do you have any ideas on why this would happen?


Kind regards
Dan

**Comment by simpleidserver** [comment]
Hello,

This exception occures when there is one sub-group which contains `members` property with no `value` property in it.
Can-you please check, when you're trying to add a nested group to a parent group, all the sub-groups contains `members.value` ?

**Comment by danflomin** [comment]
Hello

I'll check it out soon.

Nonetheless, I think that adding a child group as a member of a parent
group should be supported even if the child group is empty.

Is it possible that the Cached property has something to do with it?
Maybe the cache is not aligned to the real data?

This exception occurred while testing SCIM on a kubernetes cluster, so the
requests might have been sent to different pods.


Kind regards
Dan

**Comment by simpleidserver** [comment]
Hello, 

The cached version is aligned with the real one and deploying SCIM server on "Kubernetes" shouldn't impact its behavior.
I made some modifications in the `master` branch to ignore indirect children (Users) with no `value` in the `groups` property.
You can use this pre-release nuget package :

```
dotnet add package SimpleIdServer.Scim --version 2.0.24-ci-00395 --source https://www.myget.org/F/advance-ict/api/v3/index.json
```

Please notify me if you found `Users` in your Database with no `value` in the `groups` property.

KR,

SID

**Comment by simpleidserver** [comment]
The release `2.0.25` is published :)

KR,

SID

**Comment by danflomin** [comment]
Hello

I do not see version 2.0.25 in nuget.org.
Is it not updated there by mistake?

**Comment by simpleidserver** [comment]
Indeed the Nuget packages have not been deployed by the appveyor build.
I re-execute it & the Nuget packages are available in the `nuget.org`.

https://www.nuget.org/packages/SimpleIdServer.Scim/2.0.25
