### ISSUE TITLE
[SCIM] exception thrown on PATCH

### ISSUE THREAD

**Issue by danflomin** [simpleidserver/SimpleIdServer#404]
Hello

I've been noticing that since we upgraded our SCIM to 2.0.25 from 2.0.20 there are more exceptions of the following form.
I am not sure if this is related to the upgrade or not.

```
SimpleIdServer.Scim.Exceptions.SCIMAttributeException: not a valid attribute expression
at SimpleIdServer.Scim.Domain.SCIMRepresentationExtensions.ApplyPatches(SCIMRepresentation representation, ICollection`1 patches, IEnumerable`1 attributeMappings, Boolean ignoreUnsupportedCanonicalValues)
at SimpleIdServer.Scim.Commands.Handlers.PatchRepresentationCommandHandler.UpdateRepresentation(SCIMRepresentation existingRepresentation, PatchRepresentationCommand patchRepresentationCommand)
at SimpleIdServer.Scim.Commands.Handlers.PatchRepresentationCommandHandler.Handle(PatchRepresentationCommand patchRepresentationCommand)
at SimpleIdServer.Scim.Api.BaseApiController.InternalPatch(String id, PatchRepresentationParameter patchRepresentation)
```

What do you think?

Kind regards
Dan

**Comment by simpleidserver** [comment]
Hello,

This exception is thrown when the `path` specified in the HTTP BODY is not a valid SCIM expression OR the path doesn't respect the SCIM SCHEMA OR the `path` is valid but it is not an attribute selector : 
* orgName eq 'org' and firstName eq 'firstName' : INVALID (condition)
* orgName : VALID (attribute selector)
* emails[type eq email] : VALID (attribute selector)

I checked the difference between the version 2.0.25 and 2.0.20 and there is no major difference in the file `SCIMFilterParser`.
Can-you please monitor the incoming HTTP REQUEST and get the `path` value which cause this exception?

KR,

SID
