### ISSUE TITLE
SCIM V2.0.25 - exception on PATCH

### ISSUE THREAD

**Issue by danflomin** [simpleidserver/SimpleIdServer#449]
Hello

How are you?

I have a scenario where I get the following exception on this [line](https://github.com/simpleidserver/SimpleIdServer/blob/59e53e904c611faa5c9caa3e4cae717e3612e3fe/src/Scim/SimpleIdServer.Scim/Helpers/RepresentationReferenceSync.cs#L201).

I am not sure on how to reproduce this.
Basically I add a User to a group.
The groups has subgroups, and the user is a member of direct and indirect groups.
I am not sure if the group is a member of another, though it is very probable.

Do you have an idea on why this would happen?

```
System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
   at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at SimpleIdServer.Scim.Helpers.RepresentationReferenceSync.Sync(String resourceType, SCIMRepresentation newSourceScimRepresentation, ICollection`1 patchOperations, String location)
   at SimpleIdServer.Scim.Commands.Handlers.PatchRepresentationCommandHandler.UpdateRepresentation(SCIMRepresentation existingRepresentation, PatchRepresentationCommand patchRepresentationCommand)
   at SimpleIdServer.Scim.Commands.Handlers.PatchRepresentationCommandHandler.Handle(PatchRepresentationCommand patchRepresentationCommand)
   at SimpleIdServer.Scim.Api.BaseApiController.InternalPatch(String id, PatchRepresentationParameter patchRepresentation)
```

Kind regards
Dan

**Comment by simpleidserver** [comment]
Hello,

This problem will not occur in the version `3.0.1`, can-you please check if it is possibe to migrate to this version ?
Please read my answer in the ticket #405 .

KR,

SID
