### ISSUE TITLE
Id Server Site showing blank screen on load.

### ISSUE THREAD

**Issue by eduardk1008** [simpleidserver/SimpleIdServer#464]
I have downloaded and set up the .NET template for the ID Server and ID Server websites. Latest version (3.0.2)

I created a new project called "IdServer" from the "IdServer" template, and set up to use my local SQL Server as the data store.

I then run the project on my PC (HTTPS, port 5001) and while the site loads the navigation bar and headers, there is no content or the ability to log in using the supplied credentials. See Screenshot 1
![Screenshot_1](https://user-images.githubusercontent.com/56108178/227229948-198e7a79-1d84-4219-ae95-a38c6aa29539.png)

Also, if I click on any of the links in the navbar on this blank screen, I get an UnhandledException error (see screenshot 2):
![Screenshot_2](https://user-images.githubusercontent.com/56108178/227230132-4c6794a9-c48f-495d-a11c-5f9236833ca5.png)

For the last error, I am getting a stack trace in my console window:

 An unhandled exception has occurred while executing the request.
      System.InvalidOperationException: Cannot redirect to the authorization endpoint, the configuration may be missing or invalid.
         at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleChallengeAsyncInternal(AuthenticationProperties properties)
         at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleChallengeAsync(AuthenticationProperties properties)
         at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.ChallengeAsync(AuthenticationProperties properties)
         at Microsoft.AspNetCore.Authentication.AuthenticationService.ChallengeAsync(HttpContext context, String scheme, AuthenticationProperties properties)
         at Microsoft.AspNetCore.Mvc.ChallengeResult.ExecuteResultAsync(ActionContext context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultAsync>g__Logged|22_0(ResourceInvoker invoker, IActionResult result)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultFilters>g__Awaited|28_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at SimpleIdServer.IdServer.Middlewares.MtlsAuthenticationMiddleware.InvokeAsync(HttpContext context)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at SimpleIdServer.IdServer.Middlewares.RealmMiddleware.InvokeAsync(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

I can't find anything about this on the github or docs site.

Any help would be appreciated.

Thanks in advance.

**Comment by eduardk1008** [comment]
Just some extra information:

I tried running the site on multiple browsers (Edge, Chrome, Brave) and also tried the Docker container version included in the original source code (pulled this morning). I am experiencing the same error in the Docker version as well.

Thanks,

**Comment by eduardk1008** [comment]
Hi @simpleidserver 

Thank you so much!! I did see that, but did not think it would make that much of a difference. I made the necessary change and I can see the full screen now.

Thank you for getting back to me so promptly.

Should I close this issue?

Thank you,

Kindest regards,

Eduard Kruger.

**Comment by Thijmen** [comment]
I'm still getting the `InvalidOperationException: Cannot redirect to the authorization endpoint, the configuration may be missing or invalid.` exception, eventhough I have changed the localhost.com to localhost (also in the Clients table). What to do?

**Comment by Thijmen** [comment]
Hi @thabart , I already removed my comment as it was fixed after a clean/rebuild.
