### ISSUE TITLE
The sample encountered a problem

### ISSUE THREAD

**Issue by qq1176914912** [simpleidserver/SimpleIdServer#706]
Hello.
(CIBA) Example After receiving the verification address, enter this address and click Confirm. An error occurs:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/d70b0f1f-a61d-419c-9fd5-612cba9de6aa)
5001 Error:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/c7bd1e0a-17c3-495f-9fd7-e4a2b4fa0564)
I remember there was no problem before, I don't know why now, all the certificates have not expired.

**Comment by simpleidserver** [comment]
This issue will be fixed in the ticket #687

**Comment by simpleidserver** [comment]
This issue is fixed in the `master` branch :)

**Comment by qq1176914912** [comment]
> This issue is fixed in the `master` branch :)

1、I tested the ciba project, and I found that when I logged in with the account declared in the ciba project, the 5001 address reported an error:
![image](https://github.com/simpleidserver/SimpleIdServer/assets/79817742/6ae31d87-cc27-4eaa-87e2-28c050c09aaa)
> Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.Reflection.TargetException: Non-static method requires a target.
         at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
         at System.Reflection.PropertyInfo.GetValue(Object obj)
         at SimpleIdServer.IdServer.Extractors.PropertyClaimExtractor.Extract(HandlerContext context, IClaimMappingRule mappingRule) in D:\Aila\FW-IAM-Casbin\src\IdServer\SimpleIdServer.IdServer\Extractors\PropertyClaimExtractor.cs:line 26
         at SimpleIdServer.IdServer.Extractors.ClaimsExtractor.Extract(HandlerContext context, IEnumerable`1 mappingRules) in D:\Aila\FW-IAM-Casbin\src\IdServer\SimpleIdServer.IdServer\Extractors\ClaimsExtractor.cs:line 54
         at SimpleIdServer.IdServer.Extractors.ClaimsExtractor.ResolveGroupsAndExtract(HandlerContext context, IEnumerable`1 mappingRules) in D:\Aila\FW-IAM-Casbin\src\IdServer\SimpleIdServer.IdServer\Extractors\ClaimsExtractor.cs:line 45
         at SimpleIdServer.IdServer.Api.Token.TokenBuilders.AccessTokenBuilder.Build(BuildTokenParameter parameter, HandlerContext handlerContext, CancellationToken cancellationToken, Boolean useOriginalRequest) in D:\Aila\FW-IAM-Casbin\src\IdServer\SimpleIdServer.IdServer\Api\Token\TokenBuilders\AccessTokenBuilder.cs:line 49
         at SimpleIdServer.IdServer.Api.Token.Handlers.CIBAHandler.Handle(HandlerContext context, CancellationToken cancellationToken) in D:\Aila\FW-IAM-Casbin\src\IdServer\SimpleIdServer.IdServer\Api\Token\Handlers\CIBAHandler.cs:line 75
         at SimpleIdServer.IdServer.Api.Token.Handlers.CIBAHandler.Handle(HandlerContext context, CancellationToken cancellationToken) in D:\Aila\FW-IAM-Casbin\src\IdServer\SimpleIdServer.IdServer\Api\Token\Handlers\CIBAHandler.cs:line 123
         at SimpleIdServer.IdServer.Api.Token.TokenController.Post(String prefix, TokenRequest request, CancellationToken token) in D:\Aila\FW-IAM-Casbin\src\IdServer\SimpleIdServer.IdServer\Api\Token\TokenController.cs:line 46
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at SimpleIdServer.IdServer.Swagger.SidSwaggerUIMiddleware.Invoke(HttpContext httpContext) in D:\Aila\FW-IAM-Casbin\src\IdServer\SimpleIdServer.IdServer.Swagger\SIDSwaggerUIMiddleware.cs:line 81
         at SimpleIdServer.IdServer.Swagger.SIDSwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider) in D:\Aila\FW-IAM-Casbin\src\IdServer\SimpleIdServer.IdServer.Swagger\SIDSwaggerMiddleware.cs:line 37
         at SimpleIdServer.IdServer.Middlewares.MtlsAuthenticationMiddleware.InvokeAsync(HttpContext context) in D:\Aila\FW-IAM-Casbin\src\IdServer\SimpleIdServer.IdServer\Middlewares\MtlsAuthenticationMiddleware.cs:line 44
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at SimpleIdServer.IdServer.Middlewares.LanguageMiddleware.InvokeAsync(HttpContext context) in D:\Aila\FW-IAM-Casbin\src\IdServer\SimpleIdServer.IdServer\Middlewares\LanguageMiddleware.cs:line 28
         at SimpleIdServer.IdServer.Middlewares.RealmMiddleware.InvokeAsync(HttpContext context) in D:\Aila\FW-IAM-Casbin\src\IdServer\SimpleIdServer.IdServer\Middlewares\RealmMiddleware.cs:line 62
         at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

2、The previous problem appears again: even if I do not apply the account set in ciba, the authorization can still be successful, and "The consent is confirmed" is displayed.
https://github.com/simpleidserver/SimpleIdServer/issues/686#issuecomment-1899490583

**Comment by simpleidserver** [comment]
**CIBA Confirmation by Any User**

Security has been re-enabled in the BC Channel authorization endpoint.

**Gotify**

The goal of the Gotify notification method is to replace Firebase for receiving CIBA notifications directly in the mobile application. With this method, you can enroll the mobile application without using Firebase.

It's normal that messages are not pushed to Gotify if your user hasn't enrolled their mobile application. We will create a tutorial (Ticket #711) to explain how to enroll a mobile application with Gotify in SimpleIdServer.

In the ACRS view, we removed all PUSH methods such as Gotify and Firebase.

**Unable to Retrieve Claims (Exception)**

This issue is also fixed in the master branch.

**Comment by qq1176914912** [comment]
> **CIBA Confirmation by Any User**
> 
> Security has been re-enabled in the BC Channel authorization endpoint.
> 
> **Gotify**
> 
> The goal of the Gotify notification method is to replace Firebase for receiving CIBA notifications directly in the mobile application. With this method, you can enroll the mobile application without using Firebase.
> 
> It's normal that messages are not pushed to Gotify if your user hasn't enrolled their mobile application. We will create a tutorial (Ticket #711) to explain how to enroll a mobile application with Gotify in SimpleIdServer.
> 
> In the ACRS view, we removed all PUSH methods such as Gotify and Firebase.
> 
> **Unable to Retrieve Claims (Exception)**
> 
> This issue is also fixed in the master branch.

The problem has been resolved, thank you for your modification.
